import { useMemo } from 'react';

import { useLogoutMutation } from '../hooks/useAuthMutations';
import { useProfileQuery } from '../hooks/useProfileQuery';
import { useAuthContext } from '../context/AuthProvider';

const activityTimeline = [
  {
    title: 'Token refreshed securely',
    detail: 'Access token rotated using refresh token',
  },
  {
    title: 'Profile fetched',
    detail: 'React Query hydrated dashboard data',
  },
  {
    title: 'Session verified',
    detail: 'Protected route granted access',
  },
];

export const DashboardPage = () => {
  const { user } = useAuthContext();
  const profileQuery = useProfileQuery();
  const logoutMutation = useLogoutMutation();

  const stats = profileQuery.data?.stats;

  const quickActions = useMemo(
    () => [
      {
        label: 'Refresh data',
        helper: 'Re-fetch profile & stats',
        disabled: profileQuery.isFetching,
        onClick: () => profileQuery.refetch(),
      },
      {
        label: 'Clear session',
        helper: 'Logout and reset tokens',
        disabled: logoutMutation.isPending,
        onClick: () => logoutMutation.mutate(),
      },
    ],
    [logoutMutation, profileQuery]
  );

  return (
    <div className="dashboard-shell">
      <header className="dashboard-hero">
        <div>
          <p className="eyebrow">Welcome back</p>
          <h1>{user?.name}</h1>
          <p className="muted">{user?.email}</p>
          <p className="hint">
            Your session is protected with rotating JWT access + refresh tokens.
          </p>
        </div>
        <div className="hero-actions">
          <button
            className="ghost-button"
            onClick={() => profileQuery.refetch()}
            disabled={profileQuery.isFetching}
          >
            {profileQuery.isFetching ? 'Refreshing…' : 'Refresh data'}
          </button>
          <button
            className="primary-button"
            onClick={() => logoutMutation.mutate()}
            disabled={logoutMutation.isPending}
          >
            {logoutMutation.isPending ? 'Signing out…' : 'Logout'}
          </button>
        </div>
      </header>

      <main className="dashboard-grid">
        <section className="stats-card glass-card">
          <div className="stats-grid">
            <div>
              <p className="eyebrow">Last login</p>
              <p className="stat-value">
                {stats ? new Date(stats.lastLogin).toLocaleString() : '—'}
              </p>
            </div>
            <div>
              <p className="eyebrow">Projects</p>
              <p className="stat-value">{stats?.projects ?? '—'}</p>
              <span className="tiny muted">Mock data for UI only</span>
            </div>
            <div>
              <p className="eyebrow">Notifications</p>
              <p className="stat-value">{stats?.notifications ?? '—'}</p>
              <span className="tiny muted">Generated by API</span>
            </div>
          </div>

          {profileQuery.isLoading && <p className="muted">Loading your dashboard…</p>}
          {profileQuery.isError && (
            <p className="form-error" role="alert">
              Unable to load profile. Please refresh.
            </p>
          )}
        </section>

        <section className="panel activity-panel">
          <div className="panel-header">
            <h3>Live session timeline</h3>
            <span className="badge subtle">Real-time</span>
          </div>
          <ul className="timeline">
            {activityTimeline.map((item) => (
              <li key={item.title}>
                <div>
                  <strong>{item.title}</strong>
                  <p>{item.detail}</p>
                </div>
              </li>
            ))}
          </ul>
        </section>

        <section className="panel shortcuts-panel">
          <div className="panel-header">
            <h3>Quick actions</h3>
            <span className="muted tiny">Manage your session instantly</span>
          </div>
          <div className="shortcut-grid">
            {quickActions.map((action) => (
              <button
                key={action.label}
                className="shortcut-card"
                onClick={action.onClick}
                disabled={action.disabled}
              >
                <strong>{action.label}</strong>
                <span>{action.helper}</span>
              </button>
            ))}
          </div>
        </section>
      </main>
    </div>
  );
};
